spring.application.name=realchat

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/realchat
spring.datasource.username=root
spring.datasource.password=kopoctc

# JPA
## update : Create table if none exists, add column if field is added (use now)
## create : Deletes and recreates the table every time it is executed (data is lost)
## none : Do nothing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true